[build]
  command = "npm install"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http", "cors", "axios", "dotenv"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200